### ISSUE TITLE
"couldn't find a query runner that matches supplied arguments"

### ISSUE THREAD

**Issue by pljakobs** [fetzerch/grafana-sunandmoon-datasource#55] opened 2023-03-27 08:23 UTC
I was hoping to use sunrise and sunset times in my solar energy dashboard to scale the daily graphs to be sunrise-1h to sunset+1hr but when trying to read sunrise and sunset into dashboard variables I get the above error.
I'm no grafana expert by a long shot, but I assume that assigning variables through query is just not implemented in this module?

**Comment by fetzerch** [comment] 2023-08-26 16:13
Might be related to #50. I'm not sure if non-backend datasources support dashboard variables.

**Comment by fetzerch** [comment] 2024-08-08 06:37
Duplicate of https://github.com/fetzerch/grafana-sunandmoon-datasource/issues/50

**Closed by fetzerch** 2024-08-08 06:37 UTC
Labels: duplicate
