### ISSUE TITLE
Plugin fails to load with Grafana 8.0 (403 Forbidden Instantiating / no installed plugin with that id)

### ISSUE THREAD

**Issue by lolax80** [fetzerch/grafana-sunandmoon-datasource#45] opened 2021-07-18 06:48 UTC
I have installed per cli in docker on Grafana 8.0.6

On plugins the plugin doesn't start, its hangs on loading.
on data source under sun and moon there comes

Fetch error: 403 Forbidden Instantiating http://192.168.69.2:3000/public/plugins/fetzerch-sunandmoon-datasource/module.js Loading plugins/fetzerch-sunandmoon-datasource/module

if I click on delete data source there is
Missing valid datasource id

if I uninstall the plugin, the datasource is still there but I can't delete it, because auf missing id

**Comment by MikeyMikeDO** [comment] 2021-08-08 07:20
It would be very nice to get the plugin working with Grafana > 8.0. Many users use this plugin for visualize their solar system. I need to go back to grafana 7 because because it´s essential.

**Comment by fetzerch** [comment] 2021-08-08 19:51
@MikeyMikeDO I've played around with different Grafana and plugin versions trying to reproduce your problem, but unfortunately I can't. It's working perfectly fine here, even on 8.1.

Did you try to remove the local plugin installation directory and try reinstalling as described in https://github.com/fetzerch/grafana-sunandmoon-datasource/issues/44?

**Comment by MikeyMikeDO** [comment] 2021-08-09 03:27
Last time i tried everything possible. I thought it's an known problem on  grafana >=8.0. As soon as possible i will try iit again and give you a more detailed feedback.

**Comment by lolax80** [comment] 2021-08-09 06:28
same issue on 8.1
I can't delete the plugin. I used grafana-cli plugins remove an also deleted the plugin ordner
but there is still this
![Ohne Titel](https://user-images.githubusercontent.com/30566171/128667447-1976cca5-4e61-429a-8c71-3c29cad3adf6.jpg)
![Ohne Titel 2](https://user-images.githubusercontent.com/30566171/128667508-9de6d25a-4ce0-41e6-9f29-5e1176280584.jpg)

**Comment by fetzerch** [comment] 2021-08-09 06:54
I'd need more information and exact steps to reproduce. Is this a fresh install of Grafana or an Upgrade? Can you try moving away the Grafana data directory just to see if it's caused by older data laying around? What OS are you running Grafana on?

**Comment by lolax80** [comment] 2021-08-09 07:02
Hi it is an existing Grafana, I updated to 8.1.
It is on docker on an synology nas.

First I install with grafana-cli plugins install fetzerch-sunandmoon-datasource, and the folder is under plugins

`bash-5.1$ grafana-cli plugins install fetzerch-sunandmoon-datasource                                                           
✔ Downloaded fetzerch-sunandmoon-datasource v0.2.1 zip successfully                                                           
                                                                                                                               
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.                 
                                                                                                                               
bash-5.1$      `                                                                                                                
                               

After the restart I can find the plugin under plugins, but with no image an if click on it it doesn't start
![Ohne Titel 2](https://user-images.githubusercontent.com/30566171/128670144-d6f79d94-0255-45ff-bfbd-4394916a0e72.jpg)
                                                                                                
                        
![Ohne Titel](https://user-images.githubusercontent.com/30566171/128669822-6cf2fb57-6489-405f-8805-72653f390235.jpg)

**Comment by fetzerch** [comment] 2021-08-09 07:23
Ok, it might be that you have some remaining datasource settings in your grafana db. Unfortunately there's no user friednly way to access or delete them. But I'd be very interested to see what exactly is in there.

Do you have a way to run 'sqlite3' on the nas? Or copy the database file ('/var/lib/grafana/grafana.db') and access it from another machine. Then either 'sqlite3' or any other sqlite client would do (for example https://github.com/sqlitebrowser/sqlitebrowser).
I'd need to see the content of the data_source table:

`sudo sqlite3 /var/lib/grafana.db`, then `SELECT * FROM data_source;"

**Comment by lolax80** [comment] 2021-08-09 07:38
Kannst Du mir helfen?
can you help me?
what should I do in sqlitebrowser

**Comment by lolax80** [comment] 2021-08-09 07:39
![image](https://user-images.githubusercontent.com/30566171/128673347-043b81dd-e98c-4655-9195-390b37e6782b.png)

**Comment by lolax80** [comment] 2021-08-09 07:58
now I have deleted with the sqlitebrowser the data_source fetzerch.
but the plugin doesn't start either

**Comment by fetzerch** [comment] 2021-08-09 19:18
Hm, really poking in the dark here. The database entry didn't really look wrong.

Is there anything suspicious regarding the plugin in the grafana log?

**Comment by lolax80** [comment] 2021-08-09 20:07
Now i have deleted the data source with the sql Browser and installed the Plugin new.
The Plugin doesnt start and there is Not datasource any More.
I Think it is a Problem with the start of the plugin. 
Where is the log from grafana, Home to Listen the start of the Plugin

**Comment by fetzerch** [comment] 2021-08-09 20:10
In the meantime I found this issue in Grafana: https://github.com/grafana/grafana/issues/36563 (will be fixed in 8.1.2).
Apparently Grafana doesn't allow files that have the x-permission-bit set, which can happen on some filesystems. There's a synology user affected, maybe this is it.

Could you try executing:

```
find /var/lib/grafana/plugins/fetzerch-sunandmoon-datasource/ -type f -exec chmod -x {} +
```

Then restart Grafana?

**Comment by MikeyMikeDO** [comment] 2021-08-11 19:05
Hi. Only for your Info: I also use Grafana in Docker on a Synology NAS. Before sunday i can´t test it again.

**Comment by lolax80** [comment] 2021-08-11 19:10
Hello,

with
`find /var/lib/grafana/plugins/fetzerch-sunandmoon-datasource/ -type f -exec chmod -x {} + `

everything is working now 

thanks

**Comment by MikeyMikeDO** [comment] 2021-08-15 19:03
I tested everything before reading here. The chmod works also for me. Everything is fine again. Thank you.

**Comment by fetzerch** [comment] 2021-08-15 19:10
Thanks for confirmation, closing this issue then. One Grafana 8.1.2 is released, the chmod workaround should no longer be necessary.

**Closed by fetzerch** 2021-08-15 19:10 UTC
Labels: configuration
