### ISSUE TITLE
Does not work in public dashboards

### ISSUE THREAD

**Issue by mvwd** [fetzerch/grafana-sunandmoon-datasource#56] opened 2023-08-11 06:12 UTC
Is there any chance we can get the plugin working in public dashboards (i know that the plugin is a data source that is unsupported for public dashboards)?

It gets back with "[plugin.unavailable]" or as a popup: "Internal server error".
Grafana v10.0.3

**Comment by fetzerch** [comment] 2023-08-26 16:16
Duplicate of #50. Frontend datasources are not supported in public dashboards. See https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/#limitations.

**Closed by fetzerch** 2023-08-26 16:16 UTC
