### ISSUE TITLE
Crash / Plugin unavailable when using Expressions

### ISSUE THREAD

**Issue by SidColt** [fetzerch/grafana-sunandmoon-datasource#69] opened 2024-07-24 07:24 UTC
[sse.dataQueryError] failed to execute query [A]: [plugin.unavailable] plugin unavailable

How to reproduce: 

Create Data Query A
Create Data Query B
Create Sun and Moon Query
Create Expression $A+$B --> sun and moon stops working

![image](https://github.com/user-attachments/assets/bdf9d574-3ed8-439a-9d62-7f3bab168384)

Versions: 
Grafana 11.1.0
S&M 0.3.3

**Comment by fetzerch** [comment] 2024-07-24 12:23
Duplicate of #50.

**Closed as completed by fetzerch** 2024-07-24 12:23 UTC
Labels: duplicate
