### ISSUE TITLE
Compatible with Grafana 4.0.1?

### ISSUE THREAD

**Issue by Xsandor** [fetzerch/grafana-sunandmoon-datasource#6] opened 2016-12-03 01:16 UTC
Is the plugin tested with Grafana v4.0.1?
I have been unsuccessful with this setup, but it's my first time using the plugin, so I might be doing something wrong.

I installed it. Added a Data source and specified coordinates. Then I tried making a new panel (graph) and add sun_altitude, but nothing happens. Have I missed something?

**Comment by fetzerch** [comment] 2016-12-03 08:19
Thanks for reporting! This is indeed an issue which I was able to reproduce now starting with Grafana 4.0.0beta1.
It only happens if you try to add new metrics. Panels that were already there before the upgrade to 4.0.0 remain working, that's why I didn't notice it yet.

The source itself seems to be working, as the annotations are working. Looks like the metric selector combo box doesn't accept the input. If you leave and enter the panel setup again, it says 'select metric' as if you never selected anything. I'll try to figure out what's wrong.

**Comment by ati** [comment] 2016-12-05 09:42
Does not work for me either. Grafana 4.0.1, successfuly added and configured S&M datasource, when I select any metrics, nothing happens.

**Comment by fetzerch** [comment] 2016-12-15 19:12
Grafana 4.0 support has been fixed in v0.1.2. Please update the addon in your grafana installation.

**Closed by fetzerch** 2016-12-15 19:12 UTC
Labels: bug
